<?php
declare(strict_types=1);
require_once __DIR__.'/includes/db.php';require_once __DIR__.'/includes/vendor_theme.php';session_start();
$vendorId=filter_input(INPUT_GET,'rid',FILTER_VALIDATE_INT)?:(int)($_SESSION['vendor_id']??0);if(!$vendorId){http_response_code(400);exit('Missing vendor.');}$_SESSION['vendor_id']=$vendorId;
$stmt=$pdo->prepare("SELECT * FROM restaurants WHERE id=? AND status='active'");$stmt->execute([$vendorId]);$vendor=$stmt->fetch();if(!$vendor){http_response_code(404);exit('Storefront not found.');}$cart=$_SESSION['carts'][$vendorId]??[];
if($_SERVER['REQUEST_METHOD']==='POST'&&isset($_POST['items'])){foreach($_POST['items'] as $itemId=>$details){$qty=max(0,min(20,(int)($details['qty']??0)));if(!$qty)continue;$stmt=$pdo->prepare('SELECT * FROM menu_items WHERE id=? AND restaurant_id=?');$stmt->execute([(int)$itemId,$vendorId]);$item=$stmt->fetch();if(!$item)continue;$variants=json_decode($item['variant_options']?:'[]',true)?:[['label'=>'Standard','price'=>$item['price']]];$label=(string)($details['variant']??'');$price=null;foreach($variants as $variant)if(hash_equals((string)$variant['label'],$label)){$price=(float)$variant['price'];break;}if($price===null)continue;$key=$itemId.':'.hash('sha256',$label);$cart[$key]=['id'=>(int)$itemId,'name'=>$item['name'],'variant'=>$label,'unit_price'=>$price,'qty'=>($cart[$key]['qty']??0)+$qty];}$_SESSION['carts'][$vendorId]=$cart;}
if(isset($_GET['remove'])){unset($cart[(string)$_GET['remove']]);$_SESSION['carts'][$vendorId]=$cart;header('Location: /cart.php?rid='.$vendorId);exit;}$_SESSION['cart']=$cart;$total=array_sum(array_map(fn($row)=>$row['qty']*$row['unit_price'],$cart));
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><title>Your cart · <?= htmlspecialchars($vendor['name']) ?></title><link rel="stylesheet" href="/assets/css/storefront.css"></head><body style="<?= htmlspecialchars(vendor_theme_style($vendor)) ?>"><main class="checkout-shell"><header class="checkout-head"><a href="/shop/<?= htmlspecialchars($vendor['slug']) ?>">← Menu</a><div><span class="step-label">Step 1 of 2</span><h1>Your order</h1></div></header>
<?php if(!$cart):?><section class="panel empty"><h2>Your cart is empty</h2><p>Choose something from <?= htmlspecialchars($vendor['name']) ?>.</p><a class="primary-button" href="/shop/<?= htmlspecialchars($vendor['slug']) ?>">Browse menu <span>→</span></a></section><?php else:?><section class="panel"><?php foreach($cart as $key=>$item):?><div class="line-item"><div><strong><?= htmlspecialchars($item['name']) ?></strong><br><small><?= (int)$item['qty'] ?> × <?= htmlspecialchars($item['variant']) ?> · R<?= number_format($item['unit_price'],2) ?></small><br><a href="/cart.php?rid=<?= $vendorId ?>&remove=<?= urlencode($key) ?>">Remove</a></div><strong>R<?= number_format($item['qty']*$item['unit_price'],2) ?></strong></div><?php endforeach;?><div class="total"><span>Total</span><span>R<?= number_format($total,2) ?></span></div></section>
<form method="post" action="/confirm_order.php?rid=<?= $vendorId ?>"><section class="panel"><span class="step-label">Collection details</span><div class="field"><label for="name">Your name</label><input id="name" name="name" autocomplete="name" required maxlength="100"></div><div class="field"><label for="phone">Mobile number</label><input id="phone" type="tel" name="phone" autocomplete="tel" inputmode="tel" required maxlength="20"></div></section><button class="primary-button" type="submit"><span>Continue to payment</span><span>R<?= number_format($total,2) ?> →</span></button></form><?php endif;?></main></body></html>
