<?php
declare(strict_types=1);
require_once __DIR__ . '/includes/db.php';
require_once __DIR__ . '/includes/vendor_theme.php';
require_once __DIR__ . '/includes/rich_text.php';
require_once __DIR__ . '/includes/restaurant_service.php';
session_start();
$vendorId=filter_input(INPUT_GET,'rid',FILTER_VALIDATE_INT);$slug=trim((string)($_GET['slug']??''));if(!$vendorId&&$slug===''){http_response_code(400);exit('Missing vendor.');}
$stmt=$pdo->prepare($vendorId?"SELECT * FROM restaurants WHERE id=? AND status='active'":"SELECT * FROM restaurants WHERE slug=? AND status='active'");$stmt->execute([$vendorId?:$slug]);$vendor=$stmt->fetch();if(!$vendor){http_response_code(404);exit('Storefront not found.');}$vendorId=(int)$vendor['id'];
$table=null;$tableToken=trim((string)($_GET['table_token']??''));$isTakeaway=isset($_GET['takeaway'])&&$_GET['takeaway']==='1';
if(($vendor['service_model']??'kiosk')==='restaurant'){
    if($isTakeaway){$_SESSION['order_modes'][$vendorId]='takeaway';unset($_SESSION['table_contexts'][$vendorId]);}
    elseif($tableToken!==''){$table=dining_table_by_token($pdo,$vendorId,$tableToken);if(!$table){http_response_code(404);exit('Dining table not found.');}$_SESSION['order_modes'][$vendorId]='table';$_SESSION['table_contexts'][$vendorId]=['id'=>(int)$table['id'],'token'=>$tableToken,'name'=>$table['name']];}
    elseif(!empty($_SESSION['table_contexts'][$vendorId])){$table=$_SESSION['table_contexts'][$vendorId];$tableToken=(string)$table['token'];}
    else{http_response_code(400);exit('Please scan the QR code on your table to order.');}
}
$stmt=$pdo->prepare("SELECT * FROM menu_items WHERE restaurant_id=? ORDER BY CASE category WHEN 'Coffee' THEN 1 WHEN 'Hot Drinks' THEN 2 WHEN 'Cold Drinks' THEN 3 WHEN 'Breakfast' THEN 4 WHEN 'Bakery' THEN 5 WHEN 'Light Meals' THEN 6 WHEN 'Extras' THEN 7 ELSE 8 END, category, name");$stmt->execute([$vendorId]);$items=$stmt->fetchAll();$groups=[];foreach($items as $item)$groups[$item['category']?:'Menu'][]=$item;
$cart=$_SESSION['carts'][$vendorId]??[];$cartCount=array_sum(array_column($cart,'qty'));$cartTotal=array_sum(array_map(fn($row)=>$row['qty']*$row['unit_price'],$cart));$logout=filter_input(INPUT_GET,'logout')?:'';
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><title><?= htmlspecialchars($vendor['name']) ?> · Order online</title><link rel="stylesheet" href="/assets/css/storefront.css?v=20260903-1"></head>
<body style="<?= htmlspecialchars(vendor_theme_style($vendor)) ?>"><main class="store-shell"><header class="store-hero"<?= $vendor['hero_path']?' style="background-image:url(\''.htmlspecialchars($vendor['hero_path'],ENT_QUOTES).'\')"':'' ?>><div class="hero-content"><?php if($vendor['logo_path']):?><img class="brand-logo" src="<?= htmlspecialchars($vendor['logo_path']) ?>" alt="<?= htmlspecialchars($vendor['name']) ?> logo"><?php endif;?><h1><?= htmlspecialchars($vendor['name']) ?></h1><p><?= $table?htmlspecialchars((string)$table['name']).' · Add a round to your open bill':($isTakeaway?'Order online for collection':htmlspecialchars($vendor['storefront_message']?:'Order ahead and collect when it is ready.')) ?></p></div></header>
<?php $vendorDescription=sanitize_vendor_description($vendor['vendor_description']??'');?>
<?php if(!$groups):?><div class="empty"><h2>Nothing on the menu yet</h2><p>Please check back shortly.</p></div><?php endif;?>
<form method="post" action="/cart.php?rid=<?= $vendorId ?>" class="menu-groups"><?php foreach($groups as $category=>$categoryItems):?><details class="category-section"><summary><span><?= htmlspecialchars($category) ?></span><small><?= count($categoryItems) ?> <?= count($categoryItems)===1?'item':'items' ?></small></summary><section class="product-grid"><?php foreach($categoryItems as $item):$variants=json_decode($item['variant_options']?:'[]',true)?:[['label'=>'Standard','price'=>$item['price']]];?><article class="product"><h3><?= htmlspecialchars($item['name']) ?></h3><small>From R<?= number_format((float)min(array_column($variants,'price')),2) ?></small><div class="product-controls"><select name="items[<?= (int)$item['id'] ?>][variant]" aria-label="<?= htmlspecialchars($item['name']) ?> option"><?php foreach($variants as $variant):?><option value="<?= htmlspecialchars($variant['label']) ?>"><?= htmlspecialchars($variant['label']) ?> · R<?= number_format((float)$variant['price'],2) ?></option><?php endforeach;?></select><input type="number" name="items[<?= (int)$item['id'] ?>][qty]" value="0" min="0" max="20" inputmode="numeric" aria-label="Quantity"></div><textarea class="item-note" name="items[<?= (int)$item['id'] ?>][note]" maxlength="250" rows="2" placeholder="Special instructions (optional)" aria-label="Special instructions for <?= htmlspecialchars($item['name']) ?>"></textarea></article><?php endforeach;?></section></details><?php endforeach;?>
<?php if($items):?><div class="cart-bar"><div class="cart-bar-inner cart-actions"><button class="primary-button" type="submit"><span>Add selected items</span><span>＋</span></button><a class="secondary-button" href="/cart.php?rid=<?= $vendorId ?>"><span>View cart</span><span><?= $cartCount?$cartCount.' · R'.number_format($cartTotal,2):'Empty' ?></span></a></div></div><?php endif;?></form>
<?php if($vendorDescription!==''):?><footer class="vendor-footer vendor-introduction" aria-label="About <?= htmlspecialchars($vendor['name']) ?>"><?= $vendorDescription ?></footer><?php endif;?></main></body></html>
