<?php
declare(strict_types=1);
require_once __DIR__.'/../includes/bootstrap.php';require_once __DIR__.'/../includes/vendor_auth.php';require_once __DIR__.'/../includes/functions.php';
$slug=trim((string)($_GET['slug']??''));$stmt=$pdo->prepare("SELECT * FROM restaurants WHERE slug=? AND status='active'");$stmt->execute([$slug]);$vendor=$stmt->fetch();if(!$vendor){http_response_code(404);exit('Vendor not found.');}$vendorId=(int)$vendor['id'];$message=null;$error=null;
if(!empty($_GET['token'])){if(complete_staff_token_login($pdo,(string)$_GET['token'],$vendorId))redirect('/vendor/'.rawurlencode($slug));$error='This login link is invalid or expired.';}
if($_SERVER['REQUEST_METHOD']==='POST'&&isset($_POST['request_login'])){require_csrf();$email=strtolower(trim((string)($_POST['email']??'')));$stmt=$pdo->prepare('SELECT u.id,u.name FROM users u JOIN restaurant_users ru ON ru.user_id=u.id WHERE u.email=? AND u.active=1 AND ru.restaurant_id=? LIMIT 1');$stmt->execute([$email,$vendorId]);$user=$stmt->fetch();
 if($user){$token=bin2hex(random_bytes(32));$pdo->prepare('INSERT INTO login_tokens(user_id,token,expires_at) VALUES(?,?,DATE_ADD(NOW(),INTERVAL 10 MINUTE))')->execute([$user['id'],$token]);$url=rtrim((string)env('APP_URL'),'/').'/vendor/'.rawurlencode($slug).'?token='.urlencode($token);sendMail($email,$user['name']?:'Staff member',$vendor['name'].' staff login','<p>Your secure staff login link:</p><p><a href="'.e($url).'">Open staff portal</a></p><p>This link expires in 10 minutes.</p>');}
 $message='If the email belongs to this vendor, a login link has been sent.';
}
$authorized=staff_can_access($pdo,$vendorId);
if($authorized&&$_SERVER['REQUEST_METHOD']==='POST'&&isset($_POST['order_id'])){require_csrf();$orderId=(int)$_POST['order_id'];$status=(string)($_POST['status']??'');$allowed=['preparing','complete','collected','cancelled'];if(in_array($status,$allowed,true)){$stmt=$pdo->prepare("UPDATE orders SET status=? WHERE id=? AND restaurant_id=? AND (status IN ('paid','preparing','complete') OR credit_card_payment=1)");$stmt->execute([$status,$orderId,$vendorId]);}redirect('/vendor/'.rawurlencode($slug));}
$orders=[];if($authorized){$stmt=$pdo->prepare("SELECT o.*,GROUP_CONCAT(CONCAT(oi.quantity,'× ',m.name,IF(oi.variant_label IS NULL OR oi.variant_label='','',CONCAT(' (',oi.variant_label,')'))) ORDER BY oi.id SEPARATOR ', ') items FROM orders o LEFT JOIN order_items oi ON oi.order_id=o.id LEFT JOIN menu_items m ON m.id=oi.menu_item_id WHERE o.restaurant_id=? AND (o.status IN ('paid','preparing','complete') OR (o.credit_card_payment=1 AND o.status NOT IN ('collected','cancelled'))) GROUP BY o.id ORDER BY o.created_at");$stmt->execute([$vendorId]);$orders=$stmt->fetchAll();}
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?= e($vendor['name']) ?> staff</title><link rel="stylesheet" href="/assets/css/super-admin.css"><?php if($authorized):?><meta http-equiv="refresh" content="15"><?php endif;?></head><body><header class="topbar"><strong><?= e($vendor['name']) ?> · Staff</strong><?php if($authorized):?><a href="/staff/logout.php?slug=<?= urlencode($slug) ?>">Log out</a><?php endif;?></header><main class="container">
<?php if(!$authorized):?><section class="card" style="max-width:480px;margin:auto"><h1>Staff sign in</h1><p class="muted">Use the email address assigned to this vendor.</p><?php if($message):?><div class="notice"><?= e($message) ?></div><?php endif;?><?php if($error):?><div class="notice error"><?= e($error) ?></div><?php endif;?><form method="post"><input type="hidden" name="csrf_token" value="<?= e(csrf_token()) ?>"><input type="hidden" name="request_login" value="1"><label for="email">Email</label><input id="email" type="email" name="email" required><p><button type="submit">Email login link</button></p></form></section>
<?php else:?><div class="actions"><div><h1>Fulfilment queue</h1><p class="muted">Paid and counter-payment orders · refreshes every 15 seconds</p></div><a class="button secondary" href="/shop/<?= e($slug) ?>" target="_blank">Open customer shop</a></div><?php if(!$orders):?><section class="card empty"><h2>No orders waiting</h2></section><?php endif;?><?php foreach($orders as $order):?><section class="card"><div class="actions"><div><span class="badge"><?= e(ucfirst($order['status'])) ?></span><h2>Order #<?= (int)$order['id'] ?> · <?= e($order['name']) ?></h2></div><strong>R<?= number_format((float)$order['total'],2) ?></strong></div><p><?= e($order['items']?:'No items') ?></p><form method="post" class="actions"><input type="hidden" name="csrf_token" value="<?= e(csrf_token()) ?>"><input type="hidden" name="order_id" value="<?= (int)$order['id'] ?>"><button name="status" value="preparing">Preparing</button><button name="status" value="complete">Ready</button><button name="status" value="collected">Collected</button><button name="status" value="cancelled">Cancel</button></form></section><?php endforeach;?><?php endif;?></main></body></html>
