<?php
declare(strict_types=1);
require_once __DIR__.'/../includes/bootstrap.php';
require_once __DIR__.'/../includes/vendor_auth.php';

$slug=trim((string)($_GET['slug']??''));
$stmt=$pdo->prepare("SELECT id,name,slug,service_model FROM restaurants WHERE slug=? AND status='active' LIMIT 1");$stmt->execute([$slug]);$vendor=$stmt->fetch();
if(!$vendor){http_response_code(404);exit('Vendor not found.');}
$vendorId=(int)$vendor['id'];require_vendor_admin_access($pdo,$vendorId,$slug);
$today=date('Y-m-d');$defaultFrom=date('Y-m-d',strtotime('-6 days'));
$from=(string)($_GET['from']??$defaultFrom);$to=(string)($_GET['to']??$today);
if(!preg_match('/^\d{4}-\d{2}-\d{2}$/',$from)||!checkdate((int)substr($from,5,2),(int)substr($from,8,2),(int)substr($from,0,4)))$from=$defaultFrom;
if(!preg_match('/^\d{4}-\d{2}-\d{2}$/',$to)||!checkdate((int)substr($to,5,2),(int)substr($to,8,2),(int)substr($to,0,4)))$to=$today;
if($from>$to)[$from,$to]=[$to,$from];
$start=$from.' 00:00:00';$end=date('Y-m-d 00:00:00',strtotime($to.' +1 day'));

$stmt=$pdo->prepare("SELECT COUNT(*) orders,COALESCE(SUM(total),0) gross FROM orders WHERE restaurant_id=? AND status<>'cancelled' AND created_at>=? AND created_at<?");$stmt->execute([$vendorId,$start,$end]);$summary=$stmt->fetch();
$stmt=$pdo->prepare("SELECT COALESCE(SUM(total),0) FROM orders WHERE restaurant_id=? AND service_type<>'table' AND payment_status='paid' AND COALESCE(paid_at,created_at)>=? AND COALESCE(paid_at,created_at)<?");$stmt->execute([$vendorId,$start,$end]);$standalonePaid=(float)$stmt->fetchColumn();
$stmt=$pdo->prepare("SELECT COALESCE(SUM(tp.amount),0) paid,COALESCE(SUM(tp.tip_amount),0) tips FROM tab_payments tp JOIN table_tabs tt ON tt.id=tp.table_tab_id WHERE tt.restaurant_id=? AND tp.payment_status='paid' AND COALESCE(tp.paid_at,tp.created_at)>=? AND COALESCE(tp.paid_at,tp.created_at)<?");$stmt->execute([$vendorId,$start,$end]);$tablePaid=$stmt->fetch();
$paid=$standalonePaid+(float)$tablePaid['paid'];$tips=(float)$tablePaid['tips'];$outstanding=max(0,(float)$summary['gross']-$paid);

$stmt=$pdo->prepare("SELECT day,payment_method,SUM(amount) amount,SUM(tips) tips FROM (SELECT DATE(COALESCE(paid_at,created_at)) day,CONVERT(COALESCE(NULLIF(payment_method,''),'Other') USING utf8mb4) COLLATE utf8mb4_unicode_ci payment_method,total amount,0 tips FROM orders WHERE restaurant_id=? AND service_type<>'table' AND payment_status='paid' AND COALESCE(paid_at,created_at)>=? AND COALESCE(paid_at,created_at)<? UNION ALL SELECT DATE(COALESCE(tp.paid_at,tp.created_at)),CONVERT(COALESCE(NULLIF(tp.payment_method,''),'Other') USING utf8mb4) COLLATE utf8mb4_unicode_ci,tp.amount,tp.tip_amount FROM tab_payments tp JOIN table_tabs tt ON tt.id=tp.table_tab_id WHERE tt.restaurant_id=? AND tp.payment_status='paid' AND COALESCE(tp.paid_at,tp.created_at)>=? AND COALESCE(tp.paid_at,tp.created_at)<?) receipts GROUP BY day,payment_method ORDER BY day DESC,payment_method");$stmt->execute([$vendorId,$start,$end,$vendorId,$start,$end]);$cashups=$stmt->fetchAll();
$providerTotals=['Yoco'=>0.0,'SnapScan'=>0.0,'Zapper'=>0.0,'Direct payments'=>0.0];
foreach($cashups as $receipt){$method=strtolower((string)$receipt['payment_method']);$provider=str_contains($method,'yoco')?'Yoco':(str_contains($method,'snap')?'SnapScan':(str_contains($method,'zapper')?'Zapper':'Direct payments'));$providerTotals[$provider]+=(float)$receipt['amount'];}
$stmt=$pdo->prepare("SELECT COALESCE(oi.item_name,m.name,'Deleted product') product,COALESCE(NULLIF(oi.variant_label,''),'Standard') variant,SUM(oi.quantity) quantity,SUM(oi.quantity*oi.unit_price) revenue FROM order_items oi JOIN orders o ON o.id=oi.order_id LEFT JOIN menu_items m ON m.id=oi.menu_item_id WHERE o.restaurant_id=? AND o.status<>'cancelled' AND o.created_at>=? AND o.created_at<? GROUP BY product,variant ORDER BY quantity DESC,revenue DESC");$stmt->execute([$vendorId,$start,$end]);$products=$stmt->fetchAll();
$stmt=$pdo->prepare("SELECT DATE(created_at) day,COUNT(*) orders,SUM(total) sales,SUM(payment_status='paid') paid_orders FROM orders WHERE restaurant_id=? AND status<>'cancelled' AND created_at>=? AND created_at<? GROUP BY DATE(created_at) ORDER BY day DESC");$stmt->execute([$vendorId,$start,$end]);$dailySales=$stmt->fetchAll();
$stmt=$pdo->prepare("SELECT id,created_at,name,service_type,status,payment_status,payment_method,total FROM orders WHERE restaurant_id=? AND status<>'cancelled' AND created_at>=? AND created_at<? ORDER BY created_at DESC,id DESC LIMIT 500");$stmt->execute([$vendorId,$start,$end]);$sales=$stmt->fetchAll();
function money(float|string $amount):string{return 'R'.number_format((float)$amount,2);}
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Reports · <?=e($vendor['name'])?></title><link rel="stylesheet" href="/assets/css/super-admin.css?v=20260903-3"></head><body><header class="topbar"><a href="/vendor/<?=e($slug)?>"><?=e($vendor['name'])?> · Reports</a><a href="/vendor/<?=e($slug)?>">Kitchen queue</a></header><main class="container"><div class="actions vendor-toolbar"><div><p class="section-kicker">Vendor accounting</p><h1>Reports</h1><p class="muted">Sales, payments and tips from <?=e($from)?> to <?=e($to)?>.</p></div><div class="actions"><?php if(($vendor['service_model']??'kiosk')==='restaurant'):?><a class="button secondary" href="/vendor/<?=e($slug)?>/tables">Tables</a><?php endif;?><a class="button secondary" href="/product/<?=e($slug)?>">Products</a></div></div>
<form class="card report-filter" method="get"><label>From<input type="date" name="from" value="<?=e($from)?>"></label><label>To<input type="date" name="to" value="<?=e($to)?>"></label><button type="submit">Apply dates</button></form>
<section class="report-metrics"><article class="card report-metric"><span>Orders</span><strong><?=(int)$summary['orders']?></strong></article><article class="card report-metric"><span>Order value</span><strong><?=money($summary['gross'])?></strong></article><article class="card report-metric"><span>Payments received</span><strong><?=money($paid)?></strong></article><article class="card report-metric"><span>Tips received</span><strong><?=money($tips)?></strong></article></section>
<section class="report-metrics" aria-label="Payment provider totals"><?php foreach($providerTotals as $provider=>$amount):?><article class="card report-metric"><span><?=e($provider)?></span><strong><?=money($amount)?></strong></article><?php endforeach;?></section>
<?php if($outstanding>0):?><div class="notice">Recorded order value not yet matched by received payments: <strong><?=money($outstanding)?></strong></div><?php endif;?>
<div class="report-grid">
<section class="card report-section"><h2>Daily cash-ups</h2><div class="report-table-wrap"><table class="report-table"><thead><tr><th>Date</th><th>Method</th><th>Tips</th><th>Received</th></tr></thead><tbody><?php foreach($cashups as $row):?><tr><td><?=e($row['day'])?></td><td><?=e(ucwords(str_replace('_',' ',$row['payment_method'])))?></td><td><?=money($row['tips'])?></td><td><?=money($row['amount'])?></td></tr><?php endforeach;?><?php if(!$cashups):?><tr><td colspan="4">No payments received.</td></tr><?php endif;?></tbody></table></div></section>
<section class="card report-section"><h2>Daily sales</h2><div class="report-table-wrap"><table class="report-table"><thead><tr><th>Date</th><th>Orders</th><th>Paid orders</th><th>Value</th></tr></thead><tbody><?php foreach($dailySales as $row):?><tr><td><?=e($row['day'])?></td><td><?=(int)$row['orders']?></td><td><?=(int)$row['paid_orders']?></td><td><?=money($row['sales'])?></td></tr><?php endforeach;?><?php if(!$dailySales):?><tr><td colspan="4">No sales.</td></tr><?php endif;?></tbody></table></div></section>
<section class="card report-section full"><h2>Products sold</h2><div class="report-table-wrap"><table class="report-table"><thead><tr><th>Product</th><th>Option</th><th>Quantity</th><th>Revenue</th></tr></thead><tbody><?php foreach($products as $row):?><tr><td><?=e($row['product'])?></td><td><?=e($row['variant'])?></td><td><?=(int)$row['quantity']?></td><td><?=money($row['revenue'])?></td></tr><?php endforeach;?><?php if(!$products):?><tr><td colspan="4">No products sold.</td></tr><?php endif;?></tbody></table></div></section>
<section class="card report-section full"><h2>Sales report</h2><div class="report-table-wrap"><table class="report-table"><thead><tr><th>Order</th><th>Date</th><th>Customer</th><th>Service</th><th>Status</th><th>Payment</th><th>Total</th></tr></thead><tbody><?php foreach($sales as $row):?><tr><td>#<?=(int)$row['id']?></td><td><?=e($row['created_at'])?></td><td><?=e($row['name']?:'Guest')?></td><td><?=e(ucfirst($row['service_type']))?></td><td><?=e(ucfirst($row['status']))?></td><td><?=e($row['payment_status']==='paid'?ucwords(str_replace('_',' ',$row['payment_method']?:'Paid')):ucfirst($row['payment_status']))?></td><td><?=money($row['total'])?></td></tr><?php endforeach;?><?php if(!$sales):?><tr><td colspan="7">No sales.</td></tr><?php endif;?></tbody></table></div></section>
</div></main></body></html>
